language: java
jdk:
- oraclejdk7
before_install:
- cd osgi-source-bundles-parent
deploy:
  provider: releases
  api_key:
    secure: nsYmc/dVMjJkZ7I9x9PtaO1h5OXUgWandT5THda2utDCfuU6YKncEmmaRpuexT3Te8IDW1MkuM4EIKUsH1Arq3Am/mmUzlzL5s1u7Ht4H0sVcu0HbcMRhCNUbXD2n0+cUWXtnYSvVmmk+hpHjH49eZ2Qn2Zjk5ez4IPq7Jh6y/A=
  file:
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/btf/target/btf.source-1.2.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/jackson-annotations/target/jackson-annotations.source-2.4.3.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/jackson-core/target/jackson-core.source-2.4.3.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/jackson-coreutils/target/jackson-coreutils.source-1.8.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/jackson-databind/target/jackson-databind.source-2.4.3.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/jackson-dataformat-xml/target/jackson-dataformat-xml.source-2.4.3.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/jackson-datatype-jsr353/target/jackson-datatype-jsr353.source-2.4.3.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/jackson-module-jaxb-annotations/target/jackson-module-jaxb-annotations.source-2.4.3.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/javax.json-api/target/javax.json-api.source-1.0.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/joda-time/target/joda-time.source-2.5.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/jopt-simple/target/jopt-simple.source-4.8-beta-1.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/json-patch/target/json-patch.source-1.7.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/json-path/target/json-path.source-1.1.0.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/json-schema-core/target/json-schema-core.source-1.2.4.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/json-schema-validator/target/json-schema-validator.source-2.2.5.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/json-smart-asm/target/asm.source-1.0.2.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/msg-simple/target/msg-simple.source-1.1.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/stax2-api/target/stax2-api.source-3.1.4.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/uri-template/target/uri-template.source-0.9.jar"
    - "/home/travis/build/aborg0/osgi_source_bundles/osgi-source-bundles-parent/woodstox-core-asl/target/woodstox-core-asl.source-4.4.1.jar"
  on:
    repo: aborg0/osgi_source_bundles
    tags: true
    all_branches: true
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8b26b1ba06bf817e3e68
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
